version: "3.9"
services:
  db:
    image: postgres:16
    container_name: gestion_documental_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gestion_documental_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
